name: Terraform Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validar código Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.9

      - name: Inicializar Terraform
        run: terraform init -backend=false

      - name: Validar configuración
        run: terraform validate
